@echo off
echo Adding missing columns to ServiceRequest table...

sqlcmd -E -S "(localdb)\MSSQLLocalDB" -Q "IF EXISTS (SELECT name FROM sys.databases WHERE name = 'HomeOwnerContext-62e5969a-7f62-421f-8ff5-4fad4059ba16') BEGIN USE [HomeOwnerContext-62e5969a-7f62-421f-8ff5-4fad4059ba16]; IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[ServiceRequest]') AND name = 'date_created') BEGIN ALTER TABLE [dbo].[ServiceRequest] ADD date_created DATETIME2 NOT NULL DEFAULT GETDATE(); END; IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[ServiceRequest]') AND name = 'service_icon') BEGIN ALTER TABLE [dbo].[ServiceRequest] ADD service_icon NVARCHAR(100) NOT NULL DEFAULT '🔧'; END; IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[ServiceRequest]') AND name = 'frequency') BEGIN ALTER TABLE [dbo].[ServiceRequest] ADD frequency NVARCHAR(50) NOT NULL DEFAULT 'Once'; END; IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[ServiceRequest]') AND name = 'scheduled_time') BEGIN ALTER TABLE [dbo].[ServiceRequest] ADD scheduled_time NVARCHAR(50) NOT NULL DEFAULT '09:00'; END; IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[ServiceRequest]') AND name = 'payment_status') BEGIN ALTER TABLE [dbo].[ServiceRequest] ADD payment_status NVARCHAR(50) NOT NULL DEFAULT 'Unpaid'; END; IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[ServiceRequest]') AND name = 'notes') BEGIN ALTER TABLE [dbo].[ServiceRequest] ADD notes NVARCHAR(MAX) NOT NULL DEFAULT ''; END; IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[ServiceRequest]') AND name = 'staffNotes') BEGIN ALTER TABLE [dbo].[ServiceRequest] ADD staffNotes NVARCHAR(MAX) NOT NULL DEFAULT ''; END; END"

echo Adding missing columns to RentPayment table...

sqlcmd -E -S "(localdb)\MSSQLLocalDB" -Q "IF EXISTS (SELECT name FROM sys.databases WHERE name = 'HomeOwnerContext-62e5969a-7f62-421f-8ff5-4fad4059ba16') BEGIN USE [HomeOwnerContext-62e5969a-7f62-421f-8ff5-4fad4059ba16]; IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[RentPayment]') AND name = 'date_created') BEGIN ALTER TABLE [dbo].[RentPayment] ADD date_created DATETIME2 NOT NULL DEFAULT GETDATE(); END; IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[RentPayment]') AND name = 'transaction_id') BEGIN ALTER TABLE [dbo].[RentPayment] ADD transaction_id NVARCHAR(100) NULL; END; END"

echo Adding missing columns to FacilityReservation table...

sqlcmd -E -S "(localdb)\MSSQLLocalDB" -Q "IF EXISTS (SELECT name FROM sys.databases WHERE name = 'HomeOwnerContext-62e5969a-7f62-421f-8ff5-4fad4059ba16') BEGIN USE [HomeOwnerContext-62e5969a-7f62-421f-8ff5-4fad4059ba16]; IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[FacilityReservation]') AND name = 'date_created') BEGIN ALTER TABLE [dbo].[FacilityReservation] ADD date_created DATETIME2 NOT NULL DEFAULT GETDATE(); END; IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[FacilityReservation]') AND name = 'reservation_time') BEGIN ALTER TABLE [dbo].[FacilityReservation] ADD reservation_time NVARCHAR(50) NULL; END; IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[FacilityReservation]') AND name = 'duration_hours') BEGIN ALTER TABLE [dbo].[FacilityReservation] ADD duration_hours INT NULL; END; IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[FacilityReservation]') AND name = 'guest_count') BEGIN ALTER TABLE [dbo].[FacilityReservation] ADD guest_count INT NULL; END; IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[FacilityReservation]') AND name = 'payment_status') BEGIN ALTER TABLE [dbo].[FacilityReservation] ADD payment_status NVARCHAR(50) NULL; END; IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[FacilityReservation]') AND name = 'staff_notes') BEGIN ALTER TABLE [dbo].[FacilityReservation] ADD staff_notes NVARCHAR(MAX) NULL; END; END"

echo All column fixes completed successfully!
pause 