// <auto-generated />
using System;
using HomeOwner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeOwner.Migrations
{
    [DbContext(typeof(HomeOwnerContext))]
    [Migration("20250413191654_UpdateServiceDatabase")]
    partial class UpdateServiceDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeOwner.Models.Announcement", b =>
                {
                    b.Property<int>("announcement_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("announcement_id"));

                    b.Property<string>("author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("priority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("announcement_id");

                    b.ToTable("Announcement");
                });

            modelBuilder.Entity("HomeOwner.Models.Comment", b =>
                {
                    b.Property<int>("comment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("comment_id"));

                    b.Property<int?>("author_id")
                        .HasColumnType("int");

                    b.Property<string>("content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("post_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.HasKey("comment_id");

                    b.HasIndex("author_id");

                    b.HasIndex("post_id");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("HomeOwner.Models.Post", b =>
                {
                    b.Property<int>("post_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("post_id"));

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("post_id");

                    b.HasIndex("user_id");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("HomeOwner.Models.Report", b =>
                {
                    b.Property<int>("report_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("report_id"));

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("report_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("report_facility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("report_severity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("report_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("report_id");

                    b.HasIndex("user_id");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("HomeOwner.Models.ServiceRequest", b =>
                {
                    b.Property<int>("request_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("request_id"));

                    b.Property<int?>("Authoruser_id")
                        .HasColumnType("int");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("request_id");

                    b.HasIndex("Authoruser_id");

                    b.ToTable("ServiceRequest");

                    b.HasDiscriminator<string>("RequestType").HasValue("ServiceRequest");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HomeOwner.Models.StaffBooking", b =>
                {
                    b.Property<int>("booking_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("booking_id"));

                    b.Property<int?>("Authoruser_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("assigned_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("request_id")
                        .HasColumnType("int");

                    b.Property<string>("staff_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("booking_id");

                    b.HasIndex("Authoruser_id");

                    b.HasIndex("request_id")
                        .IsUnique()
                        .HasFilter("[request_id] IS NOT NULL");

                    b.ToTable("StaffBooking");
                });

            modelBuilder.Entity("HomeOwner.Models.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("date_created")
                        .HasColumnType("date");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("HomeOwner.Models.FacilityRequest", b =>
                {
                    b.HasBaseType("HomeOwner.Models.ServiceRequest");

                    b.Property<string>("duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("facility_date")
                        .HasColumnType("date");

                    b.Property<string>("facility_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("facility_time")
                        .HasColumnType("datetime2");

                    b.Property<int?>("guest_number")
                        .HasColumnType("int");

                    b.Property<double?>("price")
                        .HasColumnType("float");

                    b.Property<string>("purpose")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ServiceRequest", t =>
                        {
                            t.Property("price")
                                .HasColumnName("FacilityRequest_price");
                        });

                    b.HasDiscriminator().HasValue("Facility");
                });

            modelBuilder.Entity("HomeOwner.Models.MaintenanceRequest", b =>
                {
                    b.HasBaseType("HomeOwner.Models.ServiceRequest");

                    b.Property<string>("frequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("price")
                        .HasColumnType("float");

                    b.Property<DateOnly?>("service_date")
                        .HasColumnType("date");

                    b.Property<string>("service_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("service_time")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Maintenance");
                });

            modelBuilder.Entity("HomeOwner.Models.Comment", b =>
                {
                    b.HasOne("HomeOwner.Models.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("author_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HomeOwner.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("post_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Author");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("HomeOwner.Models.Post", b =>
                {
                    b.HasOne("HomeOwner.Models.User", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");
                });

            modelBuilder.Entity("HomeOwner.Models.Report", b =>
                {
                    b.HasOne("HomeOwner.Models.User", "Author")
                        .WithMany("Reports")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");
                });

            modelBuilder.Entity("HomeOwner.Models.ServiceRequest", b =>
                {
                    b.HasOne("HomeOwner.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("Authoruser_id");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("HomeOwner.Models.StaffBooking", b =>
                {
                    b.HasOne("HomeOwner.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("Authoruser_id");

                    b.HasOne("HomeOwner.Models.ServiceRequest", "ServiceRequest")
                        .WithOne("StaffBooking")
                        .HasForeignKey("HomeOwner.Models.StaffBooking", "request_id");

                    b.Navigation("Author");

                    b.Navigation("ServiceRequest");
                });

            modelBuilder.Entity("HomeOwner.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("HomeOwner.Models.ServiceRequest", b =>
                {
                    b.Navigation("StaffBooking");
                });

            modelBuilder.Entity("HomeOwner.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Posts");

                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
